language: python

matrix:
  fast_finish: true
  include:
    - python: 3.7
      env: TOXENV=checkqa


cache:
  directories:
    - $HOME/.cache/pip
    - $TRAVIS_BUILD_DIR/.tox

install:
  - pip install --upgrade pip wheel setuptools
  - pip install tox

script:
  - tox

branches:
 only:
  - master
