language: python

matrix:
  fast_finish: true
  include:
    # Python 3.5
    - python: 3.5
      env: TOXENV=py35-django20,py35-django21,py35-django22

    # Python 3.6
    - python: 3.6
      env: TOXENV=py36-django20,py36-django21,py36-django22,py36-django30

    # Python 3.7
    - python: 3.7
      env: TOXENV=py37-django20,py37-django21,py37-django22,py37-django30,checkqa

    # Python 3.8
    - python: 3.8
      env: TOXENV=py38-django22,py38-django30

    # Django Master
    - python: 3.6
      env: TOXENV=py36-djangomaster
    - python: 3.7
      env: TOXENV=py37-djangomaster
    - python: 3.8
      env: TOXENV=py38-djangomaster

  allow_failures:
    - python: 3.6
      env: TOXENV=py36-djangomaster
    - python: 3.7
      env: TOXENV=py37-djangomaster
    - python: 3.8
      env: TOXENV=py38-djangomaster

cache:
  directories:
    - $HOME/.cache/pip
    - $TRAVIS_BUILD_DIR/.tox

install:
  - pip install --upgrade pip wheel setuptools
  - pip install tox

script:
  - tox

branches:
 only:
  - master
